-- JewelEntryApp: Optimized Sales & Order Management Tables
-- This file contains optimized CREATE TABLE statements for sales management with indexes and foreign keys

CREATE TABLE `jewellery_sales` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firm_id` INT NOT NULL,
  `sale_number` VARCHAR(50) NOT NULL,
  `customer_id` INT NOT NULL,
  `sale_date` DATETIME NOT NULL,
  `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `discount_amount` DECIMAL(10,2) DEFAULT 0.00,
  `tax_amount` DECIMAL(10,2) DEFAULT 0.00,
  `grand_total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `paid_amount` DECIMAL(12,2) DEFAULT 0.00,
  `due_amount` DECIMAL(12,2) GENERATED ALWAYS AS (`grand_total` - `paid_amount`) STORED,
  `payment_status` ENUM('pending','partial','completed') DEFAULT 'pending',
  `sale_type` ENUM('retail','wholesale','exchange') DEFAULT 'retail',
  `payment_method` VARCHAR(50) DEFAULT NULL,
  `invoice_number` VARCHAR(50) DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `unique_sale_number` (`sale_number`),
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_customer_id` (`customer_id`),
  INDEX `idx_sale_date` (`sale_date`),
  INDEX `idx_payment_status` (`payment_status`),
  INDEX `idx_created_by` (`created_by`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `customer`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `firm_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jewellery_sales_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `sale_id` INT NOT NULL,
  `product_id` VARCHAR(11) NOT NULL,
  `product_name` VARCHAR(100) NOT NULL,
  `huid_code` VARCHAR(255) NOT NULL,
  `rate_24k` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `purity` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `purity_rate` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `gross_weight` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `less_weight` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `net_weight` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `metal_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `stone_type` VARCHAR(50) DEFAULT 'None',
  `stone_weight` DECIMAL(10,3) DEFAULT 0.000,
  `stone_price` DECIMAL(10,2) DEFAULT 0.00,
  `making_type` ENUM('per_gram','percentage','fixed') DEFAULT 'percentage',
  `making_rate` DECIMAL(10,2) DEFAULT 0.00,
  `making_charges` DECIMAL(10,2) DEFAULT 0.00,
  `hm_charges` DECIMAL(10,2) DEFAULT 0.00,
  `other_charges` DECIMAL(10,2) DEFAULT 0.00,
  `total_charges` DECIMAL(12,2) DEFAULT 0.00,
  `total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sale_id` (`sale_id`),
  INDEX `idx_product_id` (`product_id`),
  INDEX `idx_huid_code` (`huid_code`),
  INDEX `idx_purity` (`purity`),
  INDEX `idx_making_type` (`making_type`),
  INDEX `idx_created_at` (`created_at`),
  FOREIGN KEY (`sale_id`) REFERENCES `jewellery_sales`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jewellery_payments` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `reference_id` INT DEFAULT NULL,
  `reference_type` ENUM('customer_order','sale','loan','due_invoice','karigar_salary','purchase','expense','liability_invoice') NOT NULL,
  `party_type` ENUM('customer','karigar','vendor','staff','other','supplier') DEFAULT NULL,
  `party_id` INT DEFAULT NULL,
  `sale_id` INT DEFAULT NULL,
  `payment_type` VARCHAR(50) DEFAULT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_notes` VARCHAR(100) DEFAULT NULL,
  `reference_no` VARCHAR(50) NOT NULL,
  `remarks` TEXT DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `transctions_type` ENUM('credit','debit') NOT NULL,
  `Firm_id` INT NOT NULL DEFAULT 1,
  INDEX `idx_reference_id` (`reference_id`),
  INDEX `idx_reference_type` (`reference_type`),
  INDEX `idx_party_id` (`party_id`),
  INDEX `idx_sale_id` (`sale_id`),
  INDEX `idx_firm_id` (`Firm_id`),
  INDEX `idx_created_at` (`created_at`),
  FOREIGN KEY (`Firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`sale_id`) REFERENCES `jewellery_sales`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jewellery_price_config` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firm_id` INT NOT NULL,
  `material_type` VARCHAR(50) NOT NULL,
  `purity` DECIMAL(5,2) NOT NULL,
  `rate_per_gram` DECIMAL(10,2) NOT NULL,
  `making_charge_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `making_charge_fixed` DECIMAL(10,2) DEFAULT 0.00,
  `wastage_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `is_active` TINYINT(1) DEFAULT 1,
  `effective_date` DATE NOT NULL,
  `expiry_date` DATE DEFAULT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_material_type` (`material_type`),
  INDEX `idx_purity` (`purity`),
  INDEX `idx_effective_date` (`effective_date`),
  INDEX `idx_is_active` (`is_active`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `firm_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jewellery_customer_order` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firm_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `karigar_id` INT DEFAULT NULL,
  `order_number` VARCHAR(20) DEFAULT NULL,
  `order_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `expected_delivery_date` DATE DEFAULT NULL,
  `total_metal_amount` DECIMAL(10,2) DEFAULT NULL,
  `total_making_charges` DECIMAL(10,2) DEFAULT NULL,
  `total_stone_amount` DECIMAL(10,2) DEFAULT NULL,
  `grand_total` DECIMAL(10,2) DEFAULT NULL,
  `advance_amount` DECIMAL(10,2) DEFAULT NULL,
  `remaining_amount` DECIMAL(10,2) DEFAULT NULL,
  `payment_method` ENUM('cash','card','upi','bank_transfer') DEFAULT NULL,
  `payment_status` ENUM('pending','partial','completed') DEFAULT NULL,
  `order_status` ENUM('pending','in progress','ready','cancelled') DEFAULT NULL,
  `priority` ENUM('normal','high','urgent') DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_customer_id` (`customer_id`),
  INDEX `idx_karigar_id` (`karigar_id`),
  INDEX `idx_order_date` (`order_date`),
  INDEX `idx_order_status` (`order_status`),
  INDEX `idx_payment_status` (`payment_status`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `customer`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jewellery_order_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `karigar_id` INT NOT NULL,
  `firm_id` INT DEFAULT NULL,
  `order_id` INT DEFAULT NULL,
  `item_status` VARCHAR(50) NOT NULL,
  `item_name` VARCHAR(100) DEFAULT NULL,
  `product_type` VARCHAR(50) DEFAULT NULL,
  `design_reference` VARCHAR(100) DEFAULT NULL,
  `metal_type` VARCHAR(50) DEFAULT NULL,
  `purity` DECIMAL(5,2) DEFAULT NULL,
  `gross_weight` DECIMAL(10,3) DEFAULT NULL,
  `less_weight` DECIMAL(10,3) DEFAULT NULL,
  `net_weight` DECIMAL(10,3) DEFAULT NULL,
  `metal_amount` DECIMAL(10,2) DEFAULT NULL,
  `stone_type` VARCHAR(50) DEFAULT NULL,
  `stone_quality` VARCHAR(50) DEFAULT NULL,
  `stone_size` VARCHAR(50) DEFAULT NULL,
  `stone_quantity` INT DEFAULT NULL,
  `stone_weight` DECIMAL(10,3) DEFAULT NULL,
  `stone_unit` VARCHAR(10) DEFAULT NULL,
  `stone_price` DECIMAL(10,2) DEFAULT NULL,
  `stone_details` TEXT DEFAULT NULL,
  `making_type` ENUM('per_gram','percentage','fixed') DEFAULT NULL,
  `making_charge_input` DECIMAL(10,2) DEFAULT NULL,
  `making_charges` DECIMAL(10,2) DEFAULT NULL,
  `size_details` TEXT DEFAULT NULL,
  `design_customization` TEXT DEFAULT NULL,
  `total_estimate` DECIMAL(10,2) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `reference_images` TEXT NOT NULL,
  `created_by` INT DEFAULT NULL,
  `updated_by` INT DEFAULT NULL,
  `issued_metal_type` VARCHAR(50) DEFAULT NULL,
  `issued_purity` DECIMAL(5,2) DEFAULT NULL,
  `issued_weight` DECIMAL(10,3) DEFAULT NULL,
  INDEX `idx_karigar_id` (`karigar_id`),
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_order_id` (`order_id`),
  INDEX `idx_item_status` (`item_status`),
  INDEX `idx_created_by` (`created_by`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`order_id`) REFERENCES `jewellery_customer_order`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `firm_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 