-- JewelEntryApp: Optimized Inventory & Stock Management Tables
-- This file contains optimized CREATE TABLE statements for inventory management with indexes and foreign keys

CREATE TABLE `inventory_metals` (
  `inventory_id` INT AUTO_INCREMENT PRIMARY KEY,
  `firm_id` INT NOT NULL DEFAULT 1,
  `material_type` VARCHAR(50) NOT NULL,
  `stock_name` VARCHAR(100) NOT NULL,
  `purity` DECIMAL(50,2) NOT NULL,
  `current_stock` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `remaining_stock` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `cost_price_per_gram` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `unit_measurement` VARCHAR(20) DEFAULT 'grams',
  `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `minimum_stock_level` DECIMAL(10,3) DEFAULT 0.000,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `source_type` TEXT NOT NULL,
  `source_id` INT DEFAULT NULL,
  `total_cost` FLOAT NOT NULL,
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_material_type` (`material_type`),
  INDEX `idx_purity` (`purity`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jewellery_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firm_id` INT NOT NULL DEFAULT 1,
  `product_id` VARCHAR(11) NOT NULL,
  `source_id` INT NOT NULL,
  `source_type` VARCHAR(50) NOT NULL,
  `jewelry_type` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(50) NOT NULL,
  `material_type` ENUM('Gold','Silver') NOT NULL,
  `purity` DECIMAL(10,2) DEFAULT NULL,
  `huid_code` VARCHAR(255) NOT NULL,
  `gross_weight` DECIMAL(10,3) NOT NULL,
  `cost_price` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `less_weight` FLOAT NOT NULL,
  `net_weight` DECIMAL(10,3) NOT NULL,
  `stone_type` VARCHAR(50) DEFAULT 'None',
  `stone_weight` DECIMAL(10,3) DEFAULT 0.000,
  `stone_unit` VARCHAR(100) NOT NULL,
  `stone_color` VARCHAR(100) NOT NULL,
  `stone_clarity` VARCHAR(100) NOT NULL,
  `stone_quality` VARCHAR(50) NOT NULL DEFAULT 'none',
  `stone_price` DECIMAL(10,0) NOT NULL DEFAULT 0,
  `making_charge` DECIMAL(5,2) DEFAULT 0.00,
  `rate_per_gram` FLOAT NOT NULL,
  `description` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `making_charge_type` VARCHAR(20) DEFAULT 'percentage',
  `wastage_percentage` DECIMAL(5,2) DEFAULT 0.00,
  `status` VARCHAR(50) NOT NULL DEFAULT 'Available',
  `manufacturing_order_id` INT NOT NULL,
  `karigar_id` INT NOT NULL,
  `image_path` VARCHAR(500) NOT NULL,
  `supplier_id` INT NOT NULL,
  `Tray_no` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_product_id` (`product_id`),
  INDEX `idx_material_type` (`material_type`),
  INDEX `idx_status` (`status`),
  INDEX `idx_supplier_id` (`supplier_id`),
  INDEX `idx_karigar_id` (`karigar_id`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`supplier_id`) REFERENCES `suppliers`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `jewellery_stock_log` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firm_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `transaction_type` ENUM('IN','OUT','ADJUSTMENT','TRANSFER') NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL,
  `previous_stock` DECIMAL(10,3) NOT NULL,
  `new_stock` DECIMAL(10,3) NOT NULL,
  `reference_id` INT DEFAULT NULL,
  `reference_type` VARCHAR(50) DEFAULT NULL,
  `transaction_date` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `notes` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_item_id` (`item_id`),
  INDEX `idx_transaction_type` (`transaction_type`),
  INDEX `idx_transaction_date` (`transaction_date`),
  INDEX `idx_created_by` (`created_by`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`item_id`) REFERENCES `jewellery_items`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `firm_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `trays` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firm_id` INT DEFAULT NULL,
  `tray_number` VARCHAR(50) DEFAULT NULL,
  `tray_type` VARCHAR(50) DEFAULT NULL,
  `location` VARCHAR(100) DEFAULT NULL,
  `capacity` INT DEFAULT NULL,
  `current_items` INT DEFAULT 0,
  `description` TEXT DEFAULT NULL,
  `status` ENUM('active','inactive','maintenance') DEFAULT 'active',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_tray_number` (`tray_number`),
  INDEX `idx_status` (`status`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE `metal_purchases` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firm_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `purchase_date` DATE NOT NULL,
  `invoice_number` VARCHAR(50) DEFAULT NULL,
  `material_type` VARCHAR(50) NOT NULL,
  `purity` DECIMAL(5,2) NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `total_amount` DECIMAL(12,2) NOT NULL,
  `payment_status` ENUM('pending','partial','completed') DEFAULT 'pending',
  `payment_method` VARCHAR(50) DEFAULT NULL,
  `paid_amount` DECIMAL(12,2) DEFAULT 0.00,
  `due_amount` DECIMAL(12,2) GENERATED ALWAYS AS (`total_amount` - `paid_amount`) STORED,
  `notes` TEXT DEFAULT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_firm_id` (`firm_id`),
  INDEX `idx_supplier_id` (`supplier_id`),
  INDEX `idx_purchase_date` (`purchase_date`),
  INDEX `idx_material_type` (`material_type`),
  INDEX `idx_payment_status` (`payment_status`),
  INDEX `idx_created_by` (`created_by`),
  FOREIGN KEY (`firm_id`) REFERENCES `firm`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`supplier_id`) REFERENCES `suppliers`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `firm_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 